# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "My Awesome Website"
title_separator: "-"
name: "vtk-carrtel"
description: "Welcome to my personal website built with Jekyll and Minimal Mistakes."
url: "https://vtk-carrtel.github.io" # Your GitHub Pages URL
baseurl: "" # Leave empty for main GitHub Pages site
repository: "vtk-carrtel/vtk-carrtel.github.io" # Your repository name

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (required for Minimal Mistakes)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Author information
author:
  name: "vtk-carrtel"
  avatar: "/assets/images/bio-photo.jpg" # Optional - add your photo later
  bio: "Developer, creator, and tech enthusiast."
  location: "Somewhere on Earth"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vtk-carrtel"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vtk-carrtel"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults for posts and pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# SEO Related
google_site_verification: # Add later if needed
bing_site_verification: # Add later if needed
yandex_site_verification: # Add later if needed